name: React Native CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  JAVA_VERSION: '17'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
        if: false # Enable this when you add tests

  build-android:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, qa, staging, production]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Android
        run: |
          if [ "${{ matrix.environment }}" = "development" ]; then
            npm run android:dev
          elif [ "${{ matrix.environment }}" = "qa" ]; then
            npm run android:qa
          elif [ "${{ matrix.environment }}" = "staging" ]; then
            npm run android:stage
          else
            npm run android:prod
          fi
        env:
          EXPO_PUBLIC_ENV: ${{ matrix.environment }}

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.environment }}-apk
          path: android/app/build/outputs/apk/${{ matrix.environment }}/debug/app-${{ matrix.environment }}-debug.apk
          if-no-files-found: error

  build-ios:
    needs: test
    runs-on: macos-latest
    strategy:
      matrix:
        environment: [development, qa, staging, production]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install
          
      - name: Build iOS
        run: |
          if [ "${{ matrix.environment }}" = "development" ]; then
            npm run ios:dev
          elif [ "${{ matrix.environment }}" = "qa" ]; then
            npm run ios:qa
          elif [ "${{ matrix.environment }}" = "staging" ]; then
            npm run ios:stage
          else
            npm run ios:prod
          fi
        env:
          EXPO_PUBLIC_ENV: ${{ matrix.environment }}

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-${{ matrix.environment }}-ipa
          path: ios/build/BaseProjectMultiple-${{ matrix.environment }}.ipa
          if-no-files-found: error 